# This yaml contains all hyperparameters for the Splat-n-Replace model.
SCENE_NAME: "replica_room/room2"

gaussian:
  batch_size: 32
  num_samples: 1024
  vanilla_iterations: 30000
  feature_iterations: 10000
  template_iterations: 10000
  learning_rate: 0.001
  similarity_threshold: 0.6
  feature_dim: 32
  empty_gaussian_threshold: 1000
  mask_iterations_ratio: 0.5


mast3r:
  image_size: 512

registration:
  ## scene: replica_room/office2
  voxel_size: 0.1
  threshold: 0.2
  ## scene: replica_room/room0
  # voxel_size: 0.05
  # threshold: 0.08