# This yaml contains all hyperparameters for the Splat-n-Replace model.
SCENE_NAME: "south-building"

gaussian:
  batch_size: 32
  num_samples: 1024
  vanilla_iterations: 30000
  feature_iterations: 10000
  template_iterations: 10000
  learning_rate: 0.001
  similarity_threshold: 0.65
  feature_dim: 32
  empty_gaussian_threshold: 1000
  offsets_frozen_ratio: 0.0


mast3r:
  image_size: 512

registration:
  ## scene: replica_room/office2
  voxel_size: 0.1
  threshold: 0.2
  ## scene: replica_room/room0
  # voxel_size: 0.05
  # threshold: 0.08